import CodeBlock from '../CodeBlock'
import IC from '../InlineCode'

export default function DRFSetup() {
  return (
    <div className="doc-prose">
      <h1 className="font-serif text-4xl font-semibold mb-2 tracking-tight text-[#E8EDF5]" style={{fontFamily:'Fraunces,serif'}}>DRF Setup</h1>
      <p className="text-lg text-[#A0ABBE] mb-8 leading-relaxed">
        A complete Django REST Framework setup with serializers, ViewSets, router config, service layer, and custom permissions.
      </p>

      <h2>Serializers</h2>
      <CodeBlock lang="python" filename="payments/serializers.py">
        {`from rest_framework import serializers\nfrom .models import Payment\n\nclass InitiatePaymentSerializer(serializers.Serializer):\n    email    = serializers.EmailField()\n    amount   = serializers.DecimalField(max_digits=12, decimal_places=2, min_value=10)\n    metadata = serializers.DictField(required=False, default=dict)\n\n    def validate_amount(self, value):\n        if value < 10:\n            raise serializers.ValidationError("Minimum amount is ₦10")\n        return value\n\n\nclass PaymentSerializer(serializers.ModelSerializer):\n    amount_naira = serializers.SerializerMethodField()\n\n    class Meta:\n        model  = Payment\n        fields = [\n            "id","reference","email","amount","amount_naira",\n            "status","channel","currency","paid_at","created_at",\n        ]\n        read_only_fields = fields\n\n    def get_amount_naira(self, obj):\n        return obj.amount / 100\n\n\nclass VerifySerializer(serializers.Serializer):\n    reference = serializers.CharField(max_length=100)\n\n\nclass ChargeAuthSerializer(serializers.Serializer):\n    authorization_code = serializers.CharField()\n    email              = serializers.EmailField()\n    amount             = serializers.DecimalField(max_digits=12, decimal_places=2, min_value=10)`}
      </CodeBlock>

      <h2>Service layer</h2>
      <p>Keep API calls out of views using a dedicated service class:</p>
      <CodeBlock lang="python" filename="payments/services.py">
        {`from django.conf import settings\nfrom django.utils import timezone\nfrom .client import paystack\nfrom .models import Payment\n\n\nclass PaystackService:\n\n    @staticmethod\n    def initialize(user, email, amount, metadata=None):\n        payment = Payment.objects.create(\n            user=user, email=email,\n            amount=int(amount * 100),\n        )\n        res = paystack.post("/transaction/initialize", json={\n            "email":        email,\n            "amount":       payment.amount,\n            "reference":    str(payment.reference),\n            "callback_url": settings.PAYSTACK_CALLBACK_URL,\n            "metadata":     metadata or {},\n        })\n        body = res.json()\n        if not body["status"]:\n            payment.delete()\n            raise ValueError(body["message"])\n        return {\n            "authorization_url": body["data"]["authorization_url"],\n            "reference":         str(payment.reference),\n        }\n\n    @staticmethod\n    def verify(reference, user=None):\n        payment = Payment.objects.get(reference=reference)\n        res  = paystack.get(f"/transaction/verify/{reference}")\n        body = res.json()\n        if not body["status"]:\n            raise ValueError(body["message"])\n        tx = body["data"]\n        if tx["status"] == "success":\n            payment.status  = "success"\n            payment.channel = tx.get("channel", "")\n            payment.paid_at = timezone.now()\n            payment.save()\n        return {"status": tx["status"], "amount": tx["amount"] / 100}\n\n    @staticmethod\n    def charge_authorization(user, authorization_code, email, amount):\n        res = paystack.post("/transaction/charge_authorization", json={\n            "authorization_code": authorization_code,\n            "email":              email,\n            "amount":             int(float(amount) * 100),\n        })\n        body = res.json()\n        if body["status"] and body["data"]["status"] == "success":\n            Payment.objects.create(\n                user=user, email=email,\n                amount=int(float(amount) * 100),\n                status="success", paid_at=timezone.now()\n            )\n            return {"status": "success"}\n        raise ValueError(body.get("message", "Charge failed"))`}
      </CodeBlock>

      <h2>ViewSet</h2>
      <CodeBlock lang="python" filename="payments/viewsets.py">
        {`from rest_framework import viewsets, mixins, status\nfrom rest_framework.decorators import action\nfrom rest_framework.response import Response\nfrom rest_framework.permissions import IsAuthenticated\nfrom .models import Payment\nfrom .serializers import PaymentSerializer, InitiatePaymentSerializer\nfrom .services import PaystackService\n\n\nclass PaymentViewSet(\n    mixins.ListModelMixin,\n    mixins.RetrieveModelMixin,\n    viewsets.GenericViewSet\n):\n    serializer_class   = PaymentSerializer\n    permission_classes = [IsAuthenticated]\n\n    def get_queryset(self):\n        return Payment.objects.filter(user=self.request.user)\n\n    @action(detail=False, methods=["post"], url_path="initiate")\n    def initiate(self, request):\n        serializer = InitiatePaymentSerializer(data=request.data)\n        serializer.is_valid(raise_exception=True)\n        result = PaystackService.initialize(\n            user=request.user,\n            **serializer.validated_data,\n        )\n        return Response(result, status=status.HTTP_201_CREATED)\n\n    @action(detail=False, methods=["get"], url_path="verify")\n    def verify(self, request):\n        reference = request.query_params.get("reference")\n        result = PaystackService.verify(reference, user=request.user)\n        return Response(result)\n\n    @action(detail=False, methods=["post"], url_path="charge")\n    def charge(self, request):\n        result = PaystackService.charge_authorization(\n            user=request.user,\n            authorization_code=request.data["authorization_code"],\n            email=request.data["email"],\n            amount=request.data["amount"],\n        )\n        return Response(result)`}
      </CodeBlock>

      <h2>Router & URL config</h2>
      <CodeBlock lang="python" filename="payments/urls.py">
        {`from rest_framework.routers import DefaultRouter\nfrom django.urls import path\nfrom .viewsets import PaymentViewSet\nfrom .views import WebhookView\n\nrouter = DefaultRouter()\nrouter.register("", PaymentViewSet, basename="payment")\n\nurlpatterns = [\n    path("webhook/", WebhookView.as_view(), name="paystack-webhook"),\n] + router.urls\n\n# Auto-registered routes:\n# GET    /api/payments/            — list user payments\n# GET    /api/payments/{id}/       — retrieve payment\n# POST   /api/payments/initiate/   — start new payment\n# GET    /api/payments/verify/     — verify by reference\n# POST   /api/payments/charge/     — charge saved card`}
      </CodeBlock>
    </div>
  )
}
